


label event_emma10(replay=False):

scene x066
if incest:
    "You enter the living room and see your mom sitting on the sofa."
else:
    "You enter the living room and see Emma sitting on the sofa."
emma "Hi there!"

if not replay:
    $ emma_corruption = 10

player "Emm... Hi..."
player "*** Damn, she looks good!"
player "*** But why is she dressed up like that?!"
player "*** Too good to be true!"
emma "Hey, why are still standing over there?!"
player "Eeehhhmmm..."
emma "Come on in! I won't bite you, haha!"
player "..."
emma "Or, if I do it, I promise to be very gentle, heh!"
player "Eeeehhhmmm..."
player "*** Oh my! Is she drunk already?!"
if incest:
    "You are about to leave, when mom speaks again."
else:
    "You are about to leave, when Emma speaks again."
emma "No, seriously, you can join me, if you want to..."
emma "I have delicious wine and a good movie here..."
player "Oh, I'd love to join you!"
scene x067
"And you cautiously occupy another sofa."
player "We spend so little time together..."
player "*** Shit! Why did I say it???"
player "Not that I..."
emma "It's okay, I know what you meant..."
emma "Sometimes it's so good to know that there are other people who care about you... right?"
player "Exactly my point!"
emma "Yeah, that's what I feel now, too..."
player "*** Shit, that dress of hers is too much for me!"
player "*** It hides nothing!!!"
player "*** I bet I can see at least quarter of her ass!!!"
if incest:
    "Trying to be polite, you decide to compliment mom about her dress."
else:
    "Trying to be polite, you decide to compliment Emma about her dress."
player "You know, you look killer hot in this fantastic dress!!!"
emma "Oh, you think so?! Thanks!"
emma "What a shame the man I wore it for, didn't see me in it!"
player "Really??? But why???"
player "Something went wrong???"
emma "My whole life went wrong..."
emma "Haha, just kidding!"
emma "Yes, something went wrong. I put it on to go on a date..."
emma "On my fist date... with a man... with any man..."
player "*** What the hell is she talking about???"
player "Very bold choice for a first date, by the way..."
emma "You think so?"
emma "Doesn't matter, any way..."
player "???"
emma "Because the date never happened..."
player "Oh!"
player "*** Am I supposed to pity her or what?!"
player "*** I don't know how to act in such situations..."
emma "Yeah... I found out that he's married..."
player "Oh!"
player "Hope, you are not too upset... He's not worth it..."
emma "Aha, that's what I decided, too... after a couple of wine glasses I drank..."
emma "So, I thought I could still 'go on a date' at home... just showing off the dress, you know..."
player "Yeah, I get it! You look astonishing!"
player "*** Shit, she's really drunk!"
player "*** Least of all I need her drunken confessions!"
emma "Hey, why are you sitting over there?"
emma "Come here, jump on my lap!"
player "Excuse me?!"
player "*** She must be completely drunk if she's saying such things!"
player "*** It's insane!"
emma "I... I... said... jump onto the sofa next to me... there's plenty of room for dozen people here!"
player "Oh, okay..."
scene x068
"You take a seat in the very corner... trying not to think how close the two of you are now."
player "*** Damn! It's almost a torture!"
player "*** She... she's completely naked under that dress!!!"
emma "So, tell me: do you have a girlfriend? Are you dating?"
player "*** This dress really hides nothing! I can see every inch of her naked body!!!"
player "*** And those boobs... Oh, those boobs!!!"
emma "So, what's your secret?"
player "Ah? Sorry, I missed the question..."
emma "Haha! Yeah, I can tell!"
player "Sorry..."
emma "That's okay... So, are you currently seeing anyone?"
player "Oh! That was the question?!"
player "*** Shit, why is she asking?"
player "*** What should I tell her?"
player "*** She has her own interest?!"
player "*** No, it's stupid! What interest she could probably have???"
emma "And? What is the answer???"
player "*** Guess, I should tell her that I'm not free..."
player "Well... Of course, I'm seeing someone... But it's all a bit overcomplicated..."
emma "How come?"
player "Well... currently we are... we are... on hold!"
player "*** Yeah, that's a good answer. And it sounds quite truthful!"
emma "Oh, I'm so sorry to hear it!"
emma "But you know those young girls: they always act on a whim!"
emma "Too young and full of crap they can't distinguish a decent young man from a bad guy even if they find one..."
player "Alas!"
player "*** Wow, that sounded almost like a compliment!!!"
emma "So, don't you worry: youth is for fun, for diverse sex without commitment..."
player "*** Is she hinting at something?!"
emma "Just take your time to enjoy life while still young..."
player "Thanks for advice! I sure will..."
scene x069
"Trying to avoid further development of your 'girls dating' topic, you make an effort and concentrate on watching the film."
if incest:
    "Gradually, mom moves towards you."
else:
    "Gradually, Emma moves towards you."
"In a moment or so, she sits right next to you."
"You pretend not to see it."
player "*** She's testing me... I shouldn't be paying attention to it!"
player "*** What a boring film!"
player "*** Why would any one ever want to watch it?!"
player "*** Some stupid 'I-will-love-him-forever' drama..."
player "*** I hate it!!!"
player "*** Why are girls so fond of this dull stuff?!"
player "*** After watching such films you want to commit a suicide, because your mood is spoilt like forever..."
player "*** What's the point of watching? I don't get it, really!"
if incest:
    "Finally, you decide to share your ideas with your mom."
else:
    "Finally, you decide to share your ideas with Emma."
"You turn to her and... discover that she's asleep... almost on your shoulder."
player "*** Oh, nice! Now I'm some kind of a pillow to sleep on!"
player "*** Though... wait a second... It's a perfect opportunity!"
player "*** Now I can thoroughly examine her body without being spotted!"
player "*** That's a relief! I've been waiting for so long to do it!!!"
"And you study her with hungry eyes."
player "*** She's insanely beautiful!"
player "*** Those huge fleshy boobs are screaming for love!"
player "*** And those teasing nipples, almost sticking out of her dress..."
player "*** Wow, I love it!"
player "*** And those legs! Oh, those awesome long legs!"
player "*** That nice perfect line of her ass..."
player "*** I wish I could touch her right now..."
player "*** Oh, I'm dying to touch her..."
player "*** Actually... why not?"
player "*** Who can stop me?!"
scene x070

if not replay:
    $ gallery.add(110)
    "== SCENE UNLOCKED =="

if incest:
    "In a blink, your hand slides in between mom's legs."
else:
    "In a blink, your hand slides in between Emma's legs."
"You hold your breath afraid that she might wake up any moment now."
"But it doesn't happen."
if incest:
    "Mom is still asleep."
else:
    "Emma is still asleep."
"Or, at least, that's what you think."
emma "*** Oh, finally he's making a move!"
emma "*** What a brave young man!"
emma "*** I like it!"
"Your hand keeps moving."
emma "*** It's been so long since a man touched me!"
emma "*** It's such a pleasure to feel him over there!"
emma "*** Closer! Oh, please, closer!!!"
emma "*** I want more!!!"
"Your hand touches her pussy."
player "*** Holy shit, she's naked!"
player "*** No panties AT ALL!!!"
if incest:
    "Very gently you start rubbing mom's pussy."
else:
    "Very gently you start rubbing Emma's pussy."
emma "*** Oh, dear!"
emma "*** Oh, what a pleasure!"
player "*** Oh my! I can't take it any longer!"
player "*** She's so burning hot over there!!!"
player "*** I'm gonna explode!!!"
player "*** My cock wants her!"
player "*** Hell, I want her!"
player "*** I could fuck her right here, on this sofa!!!"
player "*** I should stop it now!"
player "*** Or I'll go crazy!!!"
emma "*** Please, please, rub my pussy!"
emma "*** Please!!!"
"She groans."
scene x071
"And you hastily pull your hand out of her groin."
"You put it onto your jeans trying to cover your boner."
if incest:
    "Next moment mom opens her eyes and quickly moves away from you."
else:
    "Next moment Emma opens her eyes and quickly moves away from you."
"She forcefully yawns."
emma "Oh, sorry! I must have fallen asleep..."
player "Yeah, I guess so..."
emma "Sorry, didn't mean to be rude..."
player "*** Shit, where is she looking?"
player "*** She's looking at my jeans!"
emma "*** Oh, my! I can see he liked our little fun time, too!"
emma "*** He's trying to hide something over there..."
emma "*** Is it... is it his penis?!"
emma "*** But why is it so huge???"
emma "*** I have to see it one day!"
emma "*** Just to check it out!"
player "You were tired, I get it."
emma "Nope, I drank too much wine..."
emma "You know, when I drink, I can't control myself..."
emma "I lose control completely!"
player "Eeehhhmmm..."
player "*** Is it some kind of a game?!"
player "*** What is she hinting at?!"
player "Oh... okay, I'll keep it in mind..."
emma "Oh, yes! Don't forget about it!!!"
emma "And now, if you'll excuse me..."
"She elegantly stands up and walks out of the room."
player "Good night!"
emma "Oh, yeah! Very good night to you, too!"

return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
