


label event_vicky8(replay=False):

if not replay:
    $ vicky_corruption = 8

scene x080
"You enter the kitchen in hopes to eat something and bump into Ashley."
player "*** Holy shit! What is she doing here???"
ashley "Hey, man, remember me?"
player "*** I wish I didn't!"
player "Hhhmmm... Ashley, right?"
ashley "Haha, right!"
ashley "But seems, you have a very short memory for a man whom I know so intimately..."
player "*** Holy crap! I knew we shouldn't have done it!!!"
player "Oh, I didn't mean..."
ashley "Oh, relax! It doesn't matter, really!"
player "..."
ashley "Wanna give it another try?"
player "Excuse me?"
ashley "I mean, I missed your cock! Let me suck it!"
ashley "Now!"
player "Oh!"
player "*** Is she crazy?"
player "Are you nuts?!"
ashley "No. Why?"
player "Because anyone can walk on us any minute now..."
ashley "Good. It means we have at least several minutes for fun..."
player "And Vicky? What if Vicky sees us?!"
ashley "Oh, come on! She's a big girl. She'll be jealous, that's it."
player "Oh!"
ashley "So?"
player "I must be losing my mind..."
ashley "Relax! You simply enjoy taking risk, I like it!"
player "*** Oh, my! What am I doing here with this horny cock-sucker?!"
scene x081
"Ashley jumps up to you and pulls your cock out of your jeans. Then she gets down on her knees."
ashley "Wow! I love it, man!"
ashley "It's beautiful! So fucking beautiful!!!"
ashley "So sucking beautiful, heh!"
player "Then suck it! What are you waiting for?!"
ashley "Don't push me! I'm getting into the mood!"
ashley "Cock-sucking is an art, don't you know it?"
player "*** It's worse than I thought! She's insane!!!"
player "*** Oh, I'll regret it later..."
scene x082
"Meanwhile Vicky enters the room."
vicky "*** Oh, my god!!! What are they doing over there???"
vicky "*** Oh, wow!!! Now I can see his penis! It's... it's... enormous!!!"
vicky "*** No wonder that slut Ashley got so excited about it!"
vicky "*** She can distinguish good penis from small one, when she sees it..."
vicky "*** So, if she's sucking Alex's for the second time, it means he's THE MAN!"
vicky "*** Damn it, I envy her!"
vicky "*** This whole thing is so easy for her!"
vicky "*** I wish I could gather enough courage to pull a stunt like that!!!"
scene x083

if not replay:
    $ gallery.add(208)
    "== SCENE UNLOCKED =="

ashley "Okay, I'm ready!"
player "*** And I'm not! Why don't yo leave me alone?!"
"Ashley sticks her tongue out and starts gently touching your cock with it."
player "Hey! It tickles!"
ashley "Okay, okay, sorry!"
ashley "Just wanted to feel it with my tongue."
player "Oh!"
"Then she starts licking it."
"Very slowly she starts with the shaft and then up and up..."
"Till she reaches the head."
"Every move of her tongue is so skillfull and passionate..."
"So precise..."
"Aimed to torture and keep on the edge..."
ashley "Nice and slow..."
ashley "Yeah, you like it!"
ashley "Relax and let me do my thing!"
player "Then shut up and do it!"
player "Anyone can enter any time now!"
scene x088
vicky "*** Enter?! Now???"
vicky "*** Oh, no! What's the fun in doing so???"
vicky "*** It's much more interesting just to watch..."
vicky "*** And learn couple of things, maybe..."
vicky "*** Or even more..."
vicky "*** Oh, my! I'm feeling sexual arousal, too..."
"Instinctively, Vicky touches her breast and begins to fondle it."
vicky "*** Oh!!!"
scene x084
"Finally, Ashley gently takes the head of your cock into her mouth."
"You groan with excitement."
player "*** Oh, at last!!!"
"Ashley wraps her lips around the head and sucks it."
"With her lips only."
player "*** She does it nice, I like it!"
player "*** But it feels more like some sort of seduction, than actual cock sucking..."
scene x089
"Vicky keeps watching."
"She gets more and more aroused."
"Hot wave of desire strikes her..."
"Making her crave for your powerful cock."
"Vicky licks her fingers."
"Then takes their tips into her mouth."
vicky "*** I wanna taste that penis, too!"
vicky "*** How it enters my mouth..."
vicky "*** That hot head touches my lips..."
vicky "*** And meets my tongue..."
vicky "*** My passionate tongue..."
vicky "*** It starts moving inside my mouth..."
vicky "*** Warm and striving..."
vicky "*** Pulsating with life..."
vicky "*** Promising pleasure and satisfaction..."
scene x095
player "*** Damn it! Vicky will definitely walk on us here!"
player "*** I can feel it's not safe!"
player "*** We should finish up asap!!!"
player "*** I can't allow this sex addict to embarrass me in front of Vicky!"
player "*** I have big plans for Vicky!"
scene x086
"So, you resolutely grab Ashley by her hair."
"And push her towards your body."
"Ashley makes an attempt to protest, but you ignore her."
"You force her to take your penis all the way down her throat."
"Ashley obeys you and diligently takes it all."
"You grin with satisfaction."
player "Yeah, that's right, baby!"
player "Suck it! Suck it now!"
"Ashley obediently sucks your cock moving thoroughly along the shaft."
player "Yeah, that feels good!"
player "Much better, yeah!"
"Ashley wraps her lips around the shaft and moves faster... and faster... and faster..."
scene x090
"At the same time, Vicky keeps watching your 'little performance'."
vicky "*** I wonder how Ashley manages to take it so deep into her mouth..."
vicky "*** I doubt it's even possible..."
"She tries to put her fingers into her mouth and almost chokes on them."
scene x091
show nullbg with hpunch
vicky "*** Nah, that's not for me!"
vicky "*** Men like it, I get it..."
vicky "*** But what's in it for girls???"
vicky "*** I don't know... Maybe, I should be practicing more?!"
vicky "*** Because from what I hear, men like girls that are good at sucking..."
vicky "*** I guess, I'll have to talk to Ashley about it..."
vicky "*** Oh, yeah, and Alex... I need his opinion, too."
"With these thoughts, Vicky leaves."
scene x086
"Ashley happens to be so skillful that for several moments you forget about everything."
"You close your eyes and let that wild passion take over."
"All you can feel are Ashley's lips covering tight every inch of your cock..."
"And moving... moving... moving..."
"You bust your load right into her mouth."
scene x087
"Ashley blinks and swallows every single drop of your cum."
"Ashley gives you a cunning smile."
ashley "Mmmmmhhhmmm, yammi-yammi!"
ashley "I'm getting used to it, you know..."
player "*** Shit, she can't be serious, can she?"
player "*** How on earth will I ever get rid of this nymphomaniac?!"

return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
