


label event_emma11(replay=False):

scene door
if incest:
    "You pass by mom's door."
else:
    "You pass by Emma's door."
player "*** She's been too quiet this evening..."
player "*** Maybe, I should stop by and say 'hi'?!"
player "*** I kinda miss her... and her awesome boobs..."
"So, you open the door to her room."

if not replay:
    $ emma_corruption = 11

scene x072
emma "Hey, Alex, that's you?!"
emma "Come on in!"
player "*** Oh, gosh! She sounds too happy to see me..."
player "*** Is she drunk again?"
player "*** And why are there candles in her room???"
player "*** Is she in some kind of a romantic mood?!"
emma "Hey, why are you still standing over there?!"
emma "While I'm waiting here?!"
player "*** My gut tells me I should be running away from her!"
scene x092
"Instead, you take a confident step forward."
emma "That's better, much better!"
emma "Listen, I need your advice on something..."
player "*** Here we come! I knew I had to run away!"
player "Yeah, what is it?"
emma "Ehm, well... It's a very delicate issue..."
emma "I don't know how to approach it..."
player "You can get right to the point, I guess."
emma "Oh, easier said than done, haha."
player "..."
if incest:
    "Mom nervously bites her lip."
else:
    "Emma nervously bites her lip."
emma "Well... they have announced a contest at our company..."
emma "A number of my coworkers are taking part..."
emma "And I thought... maybe... just maybe... I should participate, too?!"
player "Sure thing! If that's what you really want..."
player "And what's the contest about?"
scene x093
emma "See, that's the problem. Swimsuit beauty contest."
player "*** Oh, shit!!!"
emma "The owner of our company wants to make a corporate annual calendar with twelve hottest girls..."
emma "Final photoshoot will be on his yacht."
player "*** I wonder what's attracting her more: the fact that she'll be wearing a swimsuit or a chance to hook up with their big boss?!"
emma "So?"
player "So what?"
emma "So, what will you say: should I participate or not?!"
player "Well, I think you've already made up your mind..."
emma "Aha, I really want to participate!!!"
player "So, what's the problem, then?"
emma "Oh, the problem is that I still can not choose a swimsuit."
player "..."
emma "And that's where I need you!"
player "How so?"
scene x073
emma "Take a seat... and get ready to choose!"
emma "And I'll be modelling for you!!!"
player "*** Oh, shit! Is she serious now?"
player "*** She can't be serious!!!"
player "*** I'm not sure I'll be able to survive this 'modelling' thing!"
player "*** Oh, god, why me???"
player "But why me? I'm not sure I'm good at..."
emma "Oh, come on! Don't be ridiculous!"
emma "There's no such thing as 'good' or 'bad' at judging!"
emma "You simply like it or not. And you honestly say it."
emma "No other criteria applied!"
player "Well, I can't say that I'm convinced..."
emma "Please, please, I need you!"
emma "You are the only man I feel comfortable modelling for!"
player "*** I don't get it: she sees me as a man she can trust or she doesn't see me as a man at all?!"
player "Oh, okay... let's give it a try then..."
emma "But keep in mind: my suit should be killer hot!"
emma "I intend to win that contest!!!"
player "Oh, okay... I'll do my best then..."
player "*** She's obsessed with that contest..."
emma "Now, close your eyes and don't peek..."
player "???"
emma "I have to change."
emma "I'll be quick, I promise."
player "Oh, okay."
show blackbg
"You sigh and close your eyes."
player "*** What the hell is going on?"
player "*** Why is she so obsessed with that contest?!"
player "*** And isn't she a bit too old to compete with young girls?!"
player "*** I don't get it!!!"
scene x074
emma "Ta-daaaa! You can open your eyes now!"
player "Jesus Christ!"
emma "Awesome, right?"
player "*** Holy crap!!!"
player "Eeehhhmmm, I'm speechless..."
emma "Why? I need to know your honest opinion, remember?!"
player "Eeehhhmmm... yeah... well... if so, don't take it personally..."
emma "Oh?!"
player "I think it's too... too..."
emma "Bright? Too bright?!"
player "Well, that, too... But I meant... old-fashioned..."
scene x075
emma "Old-fashioned??? Bullshit! It just can't be!"
player "..."
emma "It's brand new designer thing... I bought it in New York two weeks ago... and it cost me hell of money!!!"
player "Okay, okay, don't get so offended!"
emma "Oh, hell, I am!"
player "Listen, I'm sorry for my poor choice of words, okay?"
emma "???"
player "I didn't mean 'old-fashioned' like 'not trendy'..."
emma "What did you mean, then?"
player "All I was trying to say is that it's a bit too conservative, don't you think?!"
player "I would easier picture an elderly lady wearing that thing, rather than you..."
player "It's not an appropriate outfit for a swimsuit contest... unless you compete with elderly ladies..."
emma "No, I don't!"
emma "Okay, now I get it..."
emma "Well... if you say so... you may be right..."
emma "Anyway, that's nice that I turned to you for advice... I believe, I have something else to show... "
emma "This time NOT for elderly ladies..."
player "For young, then?"
emma "Aha! You might say so... Close your eyes and don't peek!"
show blackbg
"You close your eyes again."
player "*** Hope, it's not for extremely young ladies!"
player "*** Because even in that ugly thing she looked pretty much exciting..."
player "*** And I can feel that excitement growing down my groin..."
scene x076
emma "Okay, fine! What will you say about this one?!"
player "*** Holy shit!!! What is she doing with me?!"
player "*** She wants me to die of desire?!"
emma "Hey, Alex! Hello! Are you with me?!"
player "*** No, I'm in hell!!! Stop teasing me with your naked and beautiful body!!!"
player "Hhhhmmm, eeeehhhmmmm..."
player "*** I'm having a boner!"
player "*** I can feel it!"
player "*** Oh, my, it's so embarrassing!!!"
player "*** I should try to ignore her..."
player "*** Then she'll think that I don't like that suit and she'll take it off..."
emma "Aleeeex, are you okay?!"
player "Well... I..."
emma "???"
player "I... I... I... have my doubts about this one..."
emma "Oh, you do???"
player "Yep! I don't know... Something isn't right..."
player "*** Hell, what nonsense am I telling her?!"
emma "Oh!"
player "Well... turn around, let me have full picture..."
scene x077

if not replay:
    $ gallery.add(111)
    "== SCENE UNLOCKED =="

emma "Like this?"
player "*** Holy crap!"
player "*** Why, for god's sake, why did I ask her to do it???"
player "*** Those thin threads on her ass cover NOTHING!!!"
player "*** Why even bother making them???"
player "*** Oh, my! Having this boner is almost killing me!!!"
emma "Hey, Alex, what's wrong this time?"
player "Ah? What?"
emma "I ask you what's wrong with the swimsuit this time?!"
emma "But be honest with me, I need to know!"
player "Well... Ehhmmm..."
emma "Judging by your face, you don't like this one either!"
emma "I wonder why... I thought it was okay..."
player "Well... Ehhhmmmm..."
player "*** Shit, shit, shit!!!"
player "*** What am I supposed to tell her?!"
player "*** That she looks too hot in this one?!"
player "*** And it's a torture just to look at her?!"
player "Oh, crap!"
emma "Excuse me?"
player "*** Shit, I said it outloud!"
player "It's okay. Almost okay. You look good in it, blablabla..."
scene x094
if incest:
    "Mom frowns."
else:
    "Emma frowns."
emma "Excuse me?"
player "Listen, you wanted me to be honest, right?"
emma "Well, yeah..."
player "So, this is me being honest."
player "These stupid colorful flower on your... chest... ruin it all..."
player "It looks childish, can't you see?!"
player "As if you stole it from a kid..."
emma "Well, sort of... I borrowed it from Vicky..."
player "*** Shit! When will I learn to shut up before it's too late?!"
emma "I always suspected that my daughter's taste was far from perfect... but now I see why..."
emma "Okay! Wait here, don't go anywhere!"
emma "We'll give it another try!"
player "*** Damn it! Will it ever end?!"
player "Okay."
emma "But I should warn you."
player "???"
emma "It's... it's very... provocative... to say the least..."
player "Okay, let's see it..."
show blackbg
"You close your eyes again."
player "*** Damn it! I'm scared of her 'provocative', if the previous one, in her opinion, was anywhere near 'decent'..."
player "*** I won't survive the end of this 'modelling', I can feel it..."
scene x078
emma "Okay, so, what do you think about this one?!"
emma "You like it?"
"Suddenly, you experience difficulty breathing."
player "*** What the fuck is that???"
player "*** Some strip club outfit???"
player "*** Where did she get it???"
if incest:
    "You freeze and stare at your mom unable to utter a single word."
else:
    "You freeze and stare at Emma unable to utter a single word."
emma "So?"
player "*** She is naked!!! Absolutely naked!!!"
player "*** Hell, why is she doing it to me?"
player "*** Holy shit!!!"
player "*** I can't hold it any longer!"
player "*** I'll cum right away!"
player "I... I... should go!"
scene x079
"You jump up and rush out of the room."
emma "*** Heh! That's exactly what I wanted to see."
emma "*** Judging by his 'reaction' in his pants, this swimsuit is killer hot!"
emma "*** So, I'll be wearing it for the contest, yay!!!"

return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
