


label event_vicky7(replay=False):

scene x059
if incest:
    "You enter the living room and see your sister Vicky with her best friend Ashley."
else:
    "You enter the living room and see Vicky with her best friend Ashley."
player "*** Wow, two hot girls at one place!!!"
player "*** It's my lucky day!!!"
player "Oh, hey, girls! Didn't know you were home..."
vicky "That's because we are not."
player "???"
vicky "We are at the movies. About to watch a film... Don't you see, it's a cinema hall?!"
player "Haha, very funny!"
ashley "No, seriously, we are about to watch a nice romantic comedy... Wanna join us?!"
player "Huh... And what's the entrance fee to your... cinema hall?!"
vicky "Emmm... I don't know. Yet. But we shall figure something out, right, Ashley?!"
"Ashley gives you a wild look."
ashley "Oh, yeah! We definitely will!"
"And she slowly licks her lips."
vicky "So, are you staying?"

if not replay:
    $ vicky_corruption = 7
    $ flags.add(FLAG_PLAY_ASHLEY)

player "All right, all right, I'm staying!"
ashley "Yay!!!"
player "But only if the two of you promise to behave!"
vicky "What??? We are just BFFs, not lesbian!!!"
player "What a pity! I could get used to the idea of watching the two of you having fun together..."
ashley "Oh, yeah?!"
player "But that's not what I meant!"
vicky "???"
player "Promise me, since I'm staying, there will be no sobbing in front of the flat screen..."
vicky "Oh, come on! It's not some stupid drama we are watching, it's a romcom!!!"
vicky "Besides, I'm a big girl, I can handle myself!"
"You turn to Ashley."
"She sniffs."
ashley "Crying is not an issue for me, either... But behaving... no promises here!"
player "*** What the hell is she talking about?!"
player "Ok, deal, let's watch the movie then."
scene x060
"All of a sudden, Vicky jumps up."
vicky "You two go ahead and start watching it! I... I'll be back in a minute or two..."
player "We can wait for you, no rush..."
vicky "No, no, it's okay."
vicky "As I said: go ahead, turn it on!"
"And she leaves the room."
"Puzzled, you look at Ashley."
player "Should we wait for Vicky or turn it on?!"
ashley "Oh, man! I'm so turned on already!!!"
player "*** What the hell???"
scene x061
"She lands onto the sofa next to you."
player "*** What is she doing???"
ashley "Don't you see?!"
ashley "I'm turned on from the very moment you walked in here!"
player "*** Shit, I should have taken an armchair, it would have minimized risks..."
player "Ehm... well... I..."
ashley "Shshsh, don't say anything!"
ashley "I know, Vicky is greedy and, probably, wants to keep you all to herself, but..."
player "*** What???"
ashley "But this time she'll have to share!"
player "..."
ashley "Besides..."
"She gently touches your groin."
ashley "I saw that bulge in your jeans... the other time... it looked... very... very promising!!!"
player "*** OMG!!! Is she serious???"
ashley "And I thought to myself: 'it's too good to be true!'"
player "Ehmmm..."
player "*** She's acting weird! Is she high on something???"
ashley "How can Vicky be that lucky?!"
player "Ehmmm..."
player "*** She's definitely high!!!"
player "*** If I scream for help, will Vicky rescue me???"
ashley "It's not fair!!!"
ashley "So, I decided to check it out!!!"
player "*** Oh my! What is she doing???"
ashley "You don't mind, right?!"
scene x062

if not replay:
    $ gallery.add(207)
    "== SCENE UNLOCKED =="

"The very next moment Ashley unzips your jeans."
ashley "OMG!!! That's huge! Real huge!!!"
ashley "And hard already!"
ashley "He likes me, wow!!!"
ashley "I wonder what he tastes like, hehe!"
player "*** Shit! I can't believe it's happening!!!"
"Ashley gently touches your cock with her soft lips."
player "*** What if somebody walks in?!"
player "What if Vicky gets back?"
ashley "Ahhrrr... quick..."
"And she continues sucking it."
player "*** Oh my! That's insane!!!"
player "Wait, wait! What's the rush?!"
player "Maybe, we should... go on a date first?!"
ashley "Pppfff!!!"
"And she keeps passionately kissing your cock."
player "*** Oh, boy! If she keeps doing it, I won't hold for long..."
scene x063
"Meanwhile, Vicky approaches the living room."
vicky "*** Where is Ashley? I don't see her in the armchair..."
vicky "*** What are those two up to???"
vicky "*** Holy shit!!!"
"Vicky gasps and freezes at the threshold, being unnoticed by the two of you."
vicky "*** Oh, that stupid bitch!"
vicky "*** She can't keep her hands off my man!!!"
vicky "*** He's mine! And mine only!!!"
vicky "*** I will kill her!!!"
vicky "*** Who could know that this bitch shouldn't be left alone with a guy even for a couple of minutes?!"
vicky "*** Anyway, what is she doing down there?"
vicky "*** Giving him a handjob or a blowjob?!"
vicky "*** Wow, even the very thought of such possibility sexually arouses me!!!"
vicky "*** Oh, my! I feel I'm getting wet in my panties!!!"
vicky "*** Hm, it's nice to be looking at them and... fantasizing about his penis..."
vicky "*** And they still can't see me... heh!"
scene x064
player "*** Shit! I can't relax knowing that Vicky may get back any moment now!"
player "*** Maybe, if I'm rude with Ashley, she'll leave me alone?!"
player "*** Anyway, I should exploit this opportunity up to the fullest!"
"So you place your hand on the back of Ashley's head and push her harder, forcing to take your cock deeper in."
"Ashley murmurs something, but keeps sucking your cock."
player "*** Hm, I guess, my plan failed..."
player "*** Seems, she likes me being rude..."
player "*** She's got even more excited!"
player "*** Ok, and what about this?!"
"And you push her harder making her head go lower..."
"In a moment, you feel that your cock has gone all the way up her throat."
player "*** How do you like this, hehe?!"
"But Ashley likes it just fine."
"Very diligently she keeps sucking it, taking it deep into her throat."
player "*** Wow, she's skilled!"
player "*** Maybe, I should be seeing her on a regular basis..."
"But you don't have time to think this idea over, because Ashley's moves get faster."
"And a warm wave of relief hits you."
"You cum into Ashley's throat."
player "Oh, yeah!"
player "That was good!"
scene x065
"The very next moment Vicky walks in."
player "*** Huh, that was extremely close!"
"On seeing Vicky, Ashley hurries back to her armchair."
vicky "Gotcha!!!"
"You startle."
"Vicky produces a short laughter."
vicky "Relax! Just kidding!"
vicky "Missed me?"
vicky "*** Just look at their faces: how satisfied they both are!"
vicky "*** They are almost glowing, damn it!"
ashley "Of course, we missed you! What took you so long???"
vicky "So, what were you two doing here?"
player "Emmm..."
player "*** Shit, she's suspecting something, I can feel it!"
ashley "Emmm... We... we were looking for the remote!"
vicky "Oh!"
player "*** Damn, she doesn't buy it!"
"Vicky gives you a strange look."
player "*** Shit, shit, shit!!!"
player "*** She made us, I can tell!"
player "*** Damn, I can't stay here any longer!!!"
"You stand up."
vicky "Hey, where do you think you are going?!"
player "Emmm... sorry... Just forgot... I mean remembered something... something to do..."
player "*** Damn it!"
player "I'd better go! Don't want to... to spoil your girls night in..."
vicky "Oh, how sweet of you!!!"
"But the icy look of her eyes... something in her voice... makes you uncomfortable. Very uncomfortable."
"So, you prefer to leave."

return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
